# This is a basic workflow to help you get started with Actions

name: build apk for mlkit_sample_face_detection_01

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    environment:
    # android_keystoreという名前の Environment Secrets を使用する
    # 1つの Environment Secrets に複数のSecrets(${{ secrets.XXXX }} でアクセス可能な変数)を格納することができる
      name: android_keystore

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: チェックアウト
        uses: actions/checkout@v3
      
      - name: Flutter環境をセットアップ
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.3'
          channel: 'stable'
          
      - name: keystoreをbase64でエンコードされたsecretsからデーコードしてファイルに吐き出す
        run: echo "${{ secrets.KEYSTORE }}" | base64 --decode > release.jks
        working-directory: ./mlkit_sample_face_detection_01/android/app
        
      - name: keystore.propertiesをsecretsからファイルに吐き出す
        run: echo "${{ secrets.KEYSTORE_PROPERTIES }}" > keystore.properties
        working-directory: ./mlkit_sample_face_detection_01/android/app

      - name: android用にビルド
        run: |
          flutter pub get
          flutter build apk
        working-directory: ./mlkit_sample_face_detection_01/

      - name: GitHub Pagesにデプロイ
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: mlkit_sample_face_detection_01/build/app/outputs/
